# Generated by Django 5.1.5 on 2025-02-09 13:08

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_booking_date_booking_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 13, 8, 23, 890395, tzinfo=datetime.timezone.utc)),
        ),
    ]
