# Generated by Django 5.1.5 on 2025-02-09 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_address_remove_booking_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 13, 37, 18, 372429, tzinfo=datetime.timezone.utc)),
        ),
    ]
