# Generated by Django 5.1.5 on 2025-02-10 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 14, 5, 8, 419823, tzinfo=datetime.timezone.utc)),
        ),
    ]
