# Generated by Django 5.1.5 on 2025-02-10 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 20, 42, 6, 949563, tzinfo=datetime.timezone.utc)),
        ),
    ]
