# Generated by Django 5.1.5 on 2025-02-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_address_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='name',
        ),
    ]
